---
name: Build and deploy docker image

on:
  workflow_dispatch:
    branches:
      - 'develop'
      - 'master'
      - 'releases/*'
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'releases/*'
    
jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: docker-publish
    env:
      # these are global secrets - for readonly access to artifactory
      INTERNAL_USERNAME: ${{ secrets.JFROG_USERNAME }}
      INTERNAL_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: jfrog-central
        server-username: INTERNAL_USERNAME
        server-password: INTERNAL_PASSWORD
    - name: Set Timestamp for docker image for development branch
      if: github.ref == 'refs/heads/develop'
      run: echo "TIMESTAMP=-$(date +%Y.%m.%d)" >> $GITHUB_ENV
    - name: Get Mobile Utility Server version
      run: |
        REVISION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
        echo "REVISION=$REVISION" >> $GITHUB_ENV
    - name: Prepare wars and libs
      run: |
        mvn -U -DuseInternalRepo=true --no-transfer-progress clean package
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Log in to Azure registry
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: docker/login-action@v3
      with:
        registry: https://powerauth.azurecr.io/
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push container image to Azure registry
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name == 'workflow_dispatch' }}
        platforms: linux/amd64
        tags: powerauth.azurecr.io/mobile-utility-server:${{ env.REVISION }}${{ env.TIMESTAMP }}-${{ github.sha }}
        file: ./deploy/dockerfile/runtime/Dockerfile
        context: .

